# Generated by Django 4.1.7 on 2023-03-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(choices=[('QU', 'QUADRICEPS'), ('HA', 'HAMSTRINGS'), ('SH', 'SHOULDERS'), ('FO', 'FOREARMS'), ('GL', 'GLUTEUS'), ('BA', 'BACK'), ('CH', 'CHEST'), ('CA', 'CALVES'), ('TR', 'TRICEPS'), ('BI', 'BICEPS'), ('AB', 'ABS'), ('NA', 'NOT SPECIFIED')], default='NA', max_length=2)),
                ('repetitions', models.IntegerField()),
                ('exertion_value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
            ],
        ),
    ]
