# Generated by Django 4.1.7 on 2023-03-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datum',
            unique_together={('exercise', 'data_count')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('device', 'timestamp')},
        ),
    ]
