# Generated by Django 4.1.7 on 2023-03-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('QU', 'Quadriceps'), ('HA', 'Hamstrings'), ('SH', 'Shoulders'), ('FO', 'Forearms'), ('GL', 'Gluteus'), ('BA', 'Back'), ('CH', 'Chest'), ('CA', 'Calves'), ('TR', 'Triceps'), ('BI', 'Biceps'), ('AB', 'Abdominal'), ('NA', 'Not Specified')], default='NA', max_length=2),
        ),
    ]
