# Generated by Django 4.1.7 on 2023-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_exercise_muscle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
